---

- name: TOWER | loadbalancer | Install haproxy package
  yum:
    name: haproxy
    state: installed
  tags:
  - loadbalancer

- name: TOWER | loadbalancer | Push out haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0600
  notify: restart haproxy
  tags:
  - loadbalancer

- name: TOWER | loadbalancer | Push out tower SSL pem file
  copy:
    src: tower.pem
    dest: /etc/ssl/certs/tower.pem
  notify: restart haproxy
  tags:
  - loadbalancer

- name: TOWER | loadbalancer | Start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
  tags:
  - loadbalancer

